import { useRouter } from "next/router";
import Head from 'next/head'

declare global {
  interface Window {
    _Android: {
      showLog: (arg: string) => any
      closeSplash: () => void
    }
  }
}
import React, { useCallback, useEffect, useRef, useState } from 'react'
import { PullToRefresh } from 'react-js-pull-to-refresh'

import styles from '../styles/Home.module.scss'

import PrimaryThemeSection from '../components/home/PrimaryThemeSection'
import JobMainHeader from '../components/home/JobMainHeader'
import CommonSpinner from '../components/Spinner'
import {fetchThemes} from './api/fetchThemes';

export async function getStaticProps() {
  const themes: any = await fetchThemes()
  return {
    props: {
      themes
    }
  }
}

export default function Home({themes}: {themes: any}) {
  const router = useRouter()
  const [themeList, setThemeList] = useState<any>(themes)
  const sectionRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    console.log('Android::', window._Android);
    if(window?._Android) {
      window?._Android?.showLog('Next js test!!')
      window?._Android?.closeSplash()
    }
  }, [])

  const handleRefresh = useCallback(async (): Promise<any> => {

  }, [])

  return (
      <PullToRefresh
          pullDownContent={<CommonSpinner />}
          releaseContent={<CommonSpinner />}
          refreshContent={<CommonSpinner />}
          pullDownThreshold={80}
          onRefresh={handleRefresh}
          triggerHeight={'auto'}
          backgroundColor='white'
          startInvisible={true}
      >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.css"/>
          <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick-theme.css"/>
        </Head>
        <main id='JobMainPage' className={styles.jobMainPage} ref={sectionRef}>
          <JobMainHeader jobMainRef={sectionRef} />
          <PrimaryThemeSection themeList={themeList} />
        </main>
      </PullToRefresh>
  )
}
